---
 
- name: setup nginx web server
  hosts: aws_server
  become: true


  tasks:
    - name: install nginx
      ansible.builtin.yum:
       name: ngnix
       state: present
      
    -  name: start nginx service
       ansible.builtin.service:
         name: nginx
         state: started
         enabled: yes

    - name: Create an index.html file
      ansible.builtin.copy:
        dest: /usr/share/nginx/html/index.html
        content: "<h1>Welcome to Ansible Nginx Setup</h1>"