- name: Setup nginx web server
  hosts: aws_servers
  become: true
  tasks:
    - name: Install Nginx
      ansible.builtin.yum:
        name: nginx
        state: present

    - name: Start Nginx
      ansible.builtin.service:
        name: nginx
        state: started

    - name: Create index.html file
      ansible.builtin.copy:
        dest: /usr/share/nginx/html/index.html
        content: "<h1>Welcome to Ansible Nginx Setup</h1>"
